
const data = {
  returnCode: 0,
  result: {
    llp: '商流订单',
    order: '物流订单',
    plan: '物流计划',
    dispatch: '派单中心',
    bill: '计费与对账',
    track: '物流执行',
    track_manager: '跟踪管理',
    analysis: '智能分析',
    config: '档案管理',
    platform: '平台管理',
    basic: '系统设置',

    busf: '商流订单管理',
    book: '出货预约管理',
    delivery: '交货预约管理',
    waite: '物流订单列表',

    order_input: '订单录入',
    order_split: '订单拆分',
    order_job: '订单完善',
    order_all: '订单汇总',
    reach_pay: '到付申请',
    orderError: '对接异常',
    volume_split: '货量拆分',

    plan_mainland_native_transport: '国内运输',
    plan_port_transport: '港口运输',
    plan_hk_native_transport: '香港本地运输',
    plan_native_inshore_sea_shipping: '内贸海运',

    truck: '陆运',
    mainland_native_transport: '国内运输',
    bonded_transport: '保税运输',
    native_inshore_trade: '内贸运输',
    mainland_hk_transport: '中港运输',
    port_transport: '港口运输',
    hk_native_transport: '香港本地运输',

    sea: '海运',
    sea_transport: '海运',
    agent_booking_ship: '代订舱',
    native_inshore_sea_shipping: '内贸海运',

    air_transport: '空运',
    express_delivery: '快递',
    warehouse_operation: '仓储',
    customs_service: '报关',
    transform_do: '转DO',
    railroad_transport: '铁路运输',
    barge_transport: '驳船运输',
    agent_operation: '代办及单证服务',

    receive_mgr: '应收管理',
    receive: '应收结算',
    change_receive: '应收改单',
    receivable_pay: '应收账单',
    invoice_apply: '应收发票',
    estimate_receive: '应收预结算',

    pay_mgr: '应付管理',
    pay: '应付结算',
    change_pay: '应付改单',
    due_pay: '应付账单',
    estimate_pay: '应付预结算',
    extra: '额外费用',
    other: '其他费用',

    dock_mgr: '对接管理',
    receiveError: '应收结算异常',
    payError: '应付结算异常',

    execution: '执行录入',
    execution_sea_transport: '海运',
    execution_air_transport: '空运',
    execution_express_delivery: '快递',
    execution_port_transport: '港口运输',
    execution_mainland_hk_transport: '中港运输',
    execution_bonded_transport: '保税运输',
    execution_mainland_native_transport: '国内公路运输',
    execution_hk_native_transport: '香港本地运输',
    execution_agent_booking_ship: '代订舱',
    execution_transform_do: '转DO',
    execution_agent_operation: '代操作',
    execution_native_inshore_trade: '内贸运输',
    execution_railroad_transport: '铁路运输',
    execution_warehouse_operation: '仓储',
    execution_native_inshore_sea_shipping: '内贸海运',
    execution_barge_transport: '驳船运输',
    execution_customs_service: '报关',
    load_unload: '装卸服务',
    within_port: '港内作业',


    hmbl: '提单制作',
    seafreight: '国际海运',
    airlift: '空运运输',
    railway: '铁路联运',
    barge: '驳船运输',

    document_manager: '文档管理',
    taskList:'任务单',
    logisticsList:'物流订单',

    track_mgr: '跟踪',
    track_view: '跟踪查看',
    track_dispatch: '任务单',
    track_logistics: '物流订单',
    exception_mgr: '异常管理',
    exception: '事件异常',
    orderWrong: '货物异常',
    bookingManagement:'预约管理',
    logisticsBooking:'物流订单预约',

    client_mgr: '客户',
    client_base: '基本信息',
    client_contact: '联系人',
    client_agent: '代理跟进分配',
    client_cs: '客服分配',
    client_tax: '税率档案',
    client_rate: '汇率档案',
    factory: '收发货人档案',
    customerInvoice: '客户开票档案',
    material: '物料档案',
    customerClearingUnit: '客户结算单位',
    clientShare: '客户共享',
    customerCustomaryCost: '习惯费用项',
    customerTerminal: '客户端管理',

    supplier: '供应商',
    supplier_base: '基本信息',
    supplier_contact: '联系人',
    supplier_driver: '司机档案',
    supplier_job: '合作作业单元',
    supplier_rate: '汇率档案',
    car: '车辆档案',
    supplier_suptaxrate: '税率档案',
    tenantWarehouse: '仓库档案',
    archiverService: '地点档案',
    supplierClearingUnit: '供应商结算单位',
    supplierCustomaryCost: '习惯费用项',
    supplyTerminal: '供应端管理',


    institution_mgr: '组织档案',
    institution: '组织机构',
    department: '部门档案',
    user: '用户档案',
    tenantCorporateInfo: '法人档案',

    tenantBank: '银行档案',
    molecule: '物流分子式',
    rate: '汇率档案',
    charge_item: '费用项档案',

    tenant: '租户档案',
    car_type: '车型档案',
    job: '作业单元',
    currencyFile: '货币档案',
    goods: '料品属性管理',
    area: '行政区档案管理',
    synchronous: '同步单据',
    synchronousField: '同步字段',
    lifeCycleNodeLibrary: '生命周期节点库',
    property: '预约匹配属性管理',
    dataset: '报表模板类型',
    datalib: '导入库文件',
    tenantapi: '租户可用API',
    norm: '预约匹配规则库',
    publicAuthority: '公共字典权限',
    tenantAuthorityDistribution: '租户权限分配',
    tenantAuthority: '租户字典权限',
    pdProducts: '物流产品',
    sysDictionary: '系统字典',
    executecont: '执行内容配置',
    uncopy: '不可复制模板内容定义',
    tenant_task_unit_type: '租户产品分配',
    types: '商流订单类型配置',
    formStateConfiguration: '表单状态配置',


    mode_output_design: '报表模板设计',
    define: '料品属性自定义',
    rule: '预约匹配规则管理',
    fromOddDefine: '表单单号定义',
    excelConfigLib: 'EXCEL配置库',
    roleAuthorityDistribution: '角色权限分配',
    accountManager: '用户角色分配',
    various: '商流订单类型配置',
    userOpenApi: '接口用户配置',
    operationUnitCostRelation: '作业单元费用关系',
    warehouseApi: '仓库接口设置',
    modelRelationOfOperationUnit: '作业单元车型关系',
    mouldMake: '模板制作',
    SMSmail: '通知账号配置',

    jurisdiction: '开发配置',
    jurisdiction_dataRule: '数据规则库',
    jurisdiction_dataType: '数据类型库',
    jurisdiction_tenant_rule_types: '租户数据类型分配',
    open_api_config: 'OPENAIP库',
    serviceManager: '服务管理',
    controlManager: '控制层管理',
    urlResourceLib: 'URL库管理',
    urlResource: 'URL资源分配',
    ruleFieldLibrary: '规则字段库',
    excelOutputConfiguration: 'EXCEL输出配置',
    priceProperty: '价格属性库',
    billingFactor: '计费因子库',


    role_data_authority: '角色数据权限分配',

    llp_reports: '商流报表',
    warehousereports: '入库报表',
    salereports: '销售报表',
    returnreports: '退货报表',
    allotreports: '调拨报表',
    excelReport: 'excel报表',
    sendShortMes: '短信日志',
    sendEmail: '邮件日志',

    tenantLifecycle: '租户生命周期分配',
    tenantCurrency: '租户币种',
    workPartner: '合作伙伴',
    orderCreateService: '规则条件组',
    ruleFeldDispatch: '派单规则',
    lineSeparation: '线路拆分规则',
    tenantProduct: '租户产品',
    warehouseGoods: '仓库货物属性',
    receivableRule: '应收合并规则',
    goodsHandleRule: '货物处理规则',
    billingObject: '计费对象',


    tenantConfig: '租户配置',
    platformArchives: '平台档案',
    systemConfig: '系统配置',
    systemRule: '系统规则',
    tenantRule: '租户规则',
    privilegeDispatch: '权限分配',

    userSettings: '用户设置',
    defaultOutput: '默认输出模板',
    commonOutput:'常用输出模板',

    productConfig: '产品配置',
    stockGoods: '库存货物属性',

    unitConfig: '单元配置',
    unitPlace: '单元地点路径',
    unitPlaceAllot: '单元地点路径分配',

    businessMessage:'业务消息',
    mailBook:'通讯录',
    businessNotification: '通知',
    sendMessageByShortMes: '短信日志',
    sendMessageByEmail: '邮件日志',

    expenseReport: '费用报表'
  }
};

export default data;
