import express from 'express';
import apiUser from './user';
import apiPrivilege from './privilege';
import apiInstitution from './institution';
import apiDepartment from './department';
import apiArea from './area';
import apiRate from './rate';
import apiChargeItem from './chargeItem';
import apiFromOddDefine from './fromOddDefine';
import apiCurrencyFile from './currencyFile';
import apiTenantCurrency from './tenantCurrency';
import apiSysDictionary from './sysDictionary';
import apiRoleDataAuthority from './roleDataAuthority';
import commonOutput from './commonOutput';
import defaultOutput from './defaultOutput';
import SMSmail from './SMSmail';
import messageSetting from './messageSetting';
import apiExcelConfigLib from './excelConfigLib';
import apiTenant from './tenant';
import formExpand from './formExpand';
import systemConfig from './systemConfig';
import apicommon from './common';

const api = express.Router();
api.use('/user', apiUser);
api.use('/privilege', apiPrivilege);
api.use('/institution', apiInstitution);
api.use('/department', apiDepartment);
api.use('/area', apiArea);
api.use('/rate', apiRate);
api.use('/charge_item', apiChargeItem);
api.use('/fromOddDefine', apiFromOddDefine);
api.use('/currencyFile', apiCurrencyFile);
api.use('/tenantCurrency', apiTenantCurrency);
api.use('/sysDictionary', apiSysDictionary);
api.use('/roleDataAuthority', apiRoleDataAuthority);
api.use('/commonOutput', commonOutput);
api.use('/defaultOutput', defaultOutput);
api.use('/SMSmail',SMSmail);
api.use('/messageSetting',messageSetting);
api.use('/excelConfigLib', apiExcelConfigLib);
api.use("/common", apicommon);
api.use('/tenant', apiTenant);
api.use('/formExpand', formExpand);
api.use('/systemConfig', systemConfig);
export default api;
