import express from 'express';
import apiDataSet from './dataset';
import apiModeOutputDesign from './modeOutputDesign';
import apiPublicAuthority from './publicAuthority';
import apiAccountManager from './accountManager';
import apiTenantAuthorityDistribution from './tenantAuthorityDistribution';
import apiRoleAuthorityDistribution from './roleAuthorityDistribution';
import apiDatalib from './datalib';
import apiTenantapi from './tenantapi';
import apiModeinput from './modeinput';
import apiEmailAccept from './emailAccept';
import apiCustomersArchives from './customersArchives';
import apiSuppliersArchives from './suppliersArchives';
import apiModeOutput from './modeOutput';
import customerContact from './customerContact';
import customerFactory from './customerFactory';
import customerTax from './customerTax';
import customerCost from './customerCost';
import supplierContact from './supplierContact';
import supplierCar from './supplierCar';
import supplierDriver from './supplierDriver';
import supplierSupervisor from './supplierSupervisor';
import supplierCost from './supplierCost';
import insideFactory from './insideFactory';
import insideCar from './insideCar';
import insideDriver from './insideDriver';
import insideSupervisor from './insideSupervisor';
import customerPrice from './customerPrice';
import supplierPrice from './supplierPrice';

let api = express.Router();
api.use('/dataset', apiDataSet);
api.use('/mode_output_design', apiModeOutputDesign);
api.use('/public_authority', apiPublicAuthority);
api.use('/account_manager', apiAccountManager);
api.use('/tenant_authority_distribution', apiTenantAuthorityDistribution);
api.use('/role_authority_distribution', apiRoleAuthorityDistribution);
api.use('/datalib', apiDatalib);
api.use('/tenantapi', apiTenantapi);
api.use('/modeinput', apiModeinput);
api.use('/emailAccept', apiEmailAccept);
api.use('/customersArchives', apiCustomersArchives);
api.use('/suppliersArchives', apiSuppliersArchives);
api.use('/mode_output', apiModeOutput);
api.use('/customer_contact', customerContact);
api.use('/customer_factory', customerFactory);
api.use('/customer_tax', customerTax);
api.use('/customer_cost', customerCost);
api.use('/supplier_contact', supplierContact);
api.use('/supplier_car', supplierCar);
api.use('/supplier_driver', supplierDriver);
api.use('/supplier_supervisor', supplierSupervisor);
api.use('/supplier_cost', supplierCost);
api.use('/inside_factory', insideFactory);
api.use('/inside_car', insideCar);
api.use('/inside_driver', insideDriver);
api.use('/inside_supervisor', insideSupervisor);
api.use('/customer_price', customerPrice);
api.use('/supplier_price', supplierPrice);

export default api;
